# Generated by Django 3.2.3 on 2021-07-30 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('short_description', models.CharField(max_length=1000, verbose_name='Описание отеля')),
                ('price', models.IntegerField(verbose_name='Цена за сутки')),
                ('hotel_rating', models.IntegerField(verbose_name='Рейтинг отеля')),
                ('staff_rating', models.IntegerField(verbose_name='Рейтинг персонала')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('all_hotel_rooms', models.IntegerField(verbose_name='Всего номеров')),
                ('free_hotel_rooms', models.IntegerField(verbose_name='Количество свободных номеров')),
                ('free_luxe_rooms', models.IntegerField(verbose_name='Количество свободных люкс-номеров')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('content', models.CharField(max_length=1000, verbose_name='Содержимое')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagoona.hotel')),
            ],
        ),
    ]
