# Generated by Django 3.2.3 on 2021-08-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagoona', '0002_hotel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('content', models.CharField(max_length=1000, verbose_name='Описание услуги')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=20, verbose_name='Service slug')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип номеря')),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='free_luxe_rooms',
            new_name='free_lux_rooms',
        ),
        migrations.AddField(
            model_name='hotel',
            name='in_specoffers',
            field=models.BooleanField(default=0, verbose_name='Находится в списке спецпредложений'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, verbose_name='Hotel slug'),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagoona.hotel')),
                ('type_of_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagoona.roomtypes')),
            ],
        ),
    ]
