# Generated by Django 3.2.3 on 2021-08-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagoona', '0003_auto_20210811_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lagoona.hotel'),
            preserve_default=False,
        ),
    ]
