# Generated by Django 3.2.3 on 2021-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagoona', '0004_ourservices_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('rating', models.IntegerField(verbose_name='Рейтинг предложения')),
                ('short_description', models.CharField(max_length=3000, verbose_name='Описание предложения')),
                ('slug', models.SlugField(max_length=20, verbose_name='Unique Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг предложения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='short_description',
            field=models.CharField(max_length=3000, verbose_name='Описание предложения'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='Unique Slug'),
        ),
    ]
