# Generated by Django 3.2.3 on 2021-08-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagoona', '0006_auto_20210816_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=28, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='name',
            field=models.CharField(max_length=28, verbose_name='Название'),
        ),
    ]
